spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servicehomes
    username: servicehomes
    password: servicehomes
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.servicehomes: DEBUG
    org.springframework.security: DEBUG
