spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servicehomes
    username: servicehomes
    password: servicehomes
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 0
  servlet:
    context-path: /api
