environment          = "staging"
aws_region           = "us-east-1"
project_name         = "servicehomes"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.10.0/24", "10.0.11.0/24"]
availability_zones   = ["us-east-1a", "us-east-1b"]
rds_instance_class   = "db.t3.micro"
ecs_task_cpu         = 256
ecs_task_memory      = 512
ecs_desired_count    = 1
api_image_uri        = "759655304917.dkr.ecr.us-east-1.amazonaws.com/servicehomes/api:latest"
auth0_domain         = "dev-whp2gausi3kglqlv.us.auth0.com"
auth0_audience       = "https://api.servicehomes"
db_name              = "servicehomes"
db_username          = "servicehomes_admin"
