environment          = "staging"
aws_region           = "us-east-1"
project_name         = "servicehomes"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.10.0/24", "10.0.11.0/24"]
availability_zones   = ["us-east-1a", "us-east-1b"]
rds_instance_class   = "db.t3.micro"
ecs_task_cpu         = 256
ecs_task_memory      = 512
ecs_desired_count    = 1
db_name              = "servicehomes"
db_username          = "servicehomes_admin"
