version: 2

sources:
  - name: app
    database: SERVICEHOMES
    schema: public
    tables:
      - name: users
      - name: profiles
      - name: listings
      - name: listing_categories
      - name: listing_locations
      - name: reservations
      - name: search_queries
      - name: search_clicks
      - name: outbox_events

  - name: raw
    database: SERVICEHOMES
    schema: raw
    tables:
      - name: events_stage
